### ISSUE TITLE
Offline Collector Kernel Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CdtDelta** [Velocidex/velociraptor#1285]
Version 0.6.1

Offline Collector Config:
```
autoexec:
  argv:
  - artifacts
  - collect
  - Collector
  - --logfile
  - Collector_velociraptor-v0.6.1-windows-amd64.exe.log
  - -v
  - --require_admin
  - --prompt
  artifact_definitions:
  - name: Custom.Windows.Memory.Surge.Collect
    description: |
      Acquires a full memory image using surge-collect

      NOTE: This artifact usually takes a long time. You should increase
      the default timeout to allow it to complete.
    tools:
    - name: SurgeCollect
    sources:
    - precondition: |2

        SELECT OS From info() where OS = 'windows'
      query: |
        LET hostname <= SELECT Fqdn from info()
        LET surge <= SELECT FullPath, tempdir() AS TempDir
        FROM Artifact.Generic.Utils.FetchBinary(
          ToolName="SurgeCollect")

        SELECT StdOut FROM execve(argv=[surge[0].FullPath, "", "--accept-eula",
          hostname[0].Fqdn + "-mem"]) WHERE surge
      queries:
      - LET hostname<=SELECT Fqdn FROM info()
      - LET surge<=SELECT FullPath, tempdir() AS TempDir FROM Artifact.Generic.Utils.FetchBinary(ToolName="SurgeCollect")
      - SELECT StdOut FROM execve(argv= [surge[0].FullPath, "", "--accept-eula",
        hostname[0].Fqdn + "-mem"]) WHERE surge
  - name: Collector
    parameters:
    - name: Artifacts
      default: |-
        [
         "Custom.Windows.Memory.Surge.Collect",
         "Generic.Client.Info",
         "Generic.System.Pstree",
         "Windows.Analysis.EvidenceOfExecution",
         "Windows.Forensics.Bam",
         "Windows.Network.NetstatEnriched",
         "Windows.Packs.LateralMovement",
         "Windows.Packs.Persistence",
         "Windows.Registry.EnabledMacro",
         "Windows.Registry.MountPoints2",
         "Windows.Registry.PortProxy",
         "Windows.KapeFiles.Targets"
        ]
      type: json_array
    - name: Parameters
      default: |-
        {
         "Windows.KapeFiles.Targets": {
          "_BasicCollection": "Y",
          "_Boot": "Y",
          "_J": "Y",
          "_LogFile": "Y",
          "_MFT": "Y",
          "_MFTMirr": "Y",
          "_SDS": "Y",
          "_T": "Y",
          "AVG": "Y",
          "AceText": "Y",
          "AcronisTrueImage": "Y",
          "Ammyy": "Y",
          "Antivirus": "Y",
          "AnyDesk": "Y",
          "ApacheAccessLog": "Y",
          "AsperaConnect": "Y",
          "Avast": "Y",
          "AviraAVLogs": "Y",
          "BITS": "Y",
          "BitTorrent": "Y",
          "Bitdefender": "Y",
          "CertUtil": "Y",
          "CiscoJabber": "Y",
          "CloudStorage": "Y",
          "ComboFix": "Y",
          "ConfluenceLogs": "Y",
          "Cybereason": "Y",
          "DC__": "Y",
          "DirectoryTraversal_AudioFiles": "N",
          "DirectoryTraversal_ExcelDocuments": "Y",
          "DirectoryTraversal_PDFDocuments": "Y",
          "DirectoryTraversal_PictureFiles": "Y",
          "DirectoryTraversal_SQLiteDatabases": "Y",
          "DirectoryTraversal_WordDocuments": "Y",
          "Discord": "Y",
          "ESET": "Y",
          "Edge": "Y",
          "EdgeChromium": "Y",
          "Emsisoft": "Y",
          "EventTraceLogs": "Y",
          "EventTranscriptDB": "Y",
          "Exchange": "Y",
          "ExchangeClientAccess": "Y",
          "ExchangeCve_2021_26855": "Y",
          "ExchangeTransport": "Y",
          "FSecure": "Y",
          "FileZillaClient": "Y",
          "FileZillaServer": "Y",
          "FreeFileSync": "Y",
          "FrostWire": "Y",
          "Gigatribe": "Y",
          "GroupPolicy": "Y",
          "HitmanPro": "Y",
          "IISLogFiles": "Y",
          "IRCClients": "Y",
          "JavaWebCache": "Y",
          "Kali": "Y",
          "Kaseya": "Y",
          "LinuxOnWindowsProfileFiles": "Y",
          "LogFiles": "Y",
          "LogMeIn": "Y",
          "MSSQLErrorLog": "Y",
          "MacriumReflect": "Y",
          "Malwarebytes": "Y",
          "ManageEngineLogs": "Y",
          "Mattermost": "Y",
          "McAfee": "Y",
          "McAfee_ePO": "Y",
          "MemoryFiles": "Y",
          "MicrosoftTeams": "Y",
          "NGINXLogs": "Y",
          "OpenSSHClient": "Y",
          "OpenSSHServer": "Y",
          "OpenVPNClient": "Y",
          "Opera": "Y",
          "P2PClients": "Y",
          "PeaZip": "Y",
          "PowerShellConsole": "Y",
          "ProtonVPN": "Y",
          "PuffinSecureBrowser": "Y",
          "QFinderPro__QNAP_": "Y",
          "RDPCache": "Y",
          "RDPLogs": "Y",
          "Radmin": "Y",
          "RecycleBin": "Y",
          "RemoteAdmin": "Y",
          "RogueKiller": "Y",
          "SDB": "Y",
          "SRUM": "Y",
          "SUPERAntiSpyware": "Y",
          "SUSELinuxEnterpriseServer": "Y",
          "ScheduledTasks": "Y",
          "ScreenConnect": "Y",
          "SecureAge": "Y",
          "SentinelOne": "Y",
          "Shareaza": "Y",
          "ShareX": "Y",
          "Skype": "Y",
          "Slack": "Y",
          "Sophos": "Y",
          "Soulseek": "Y",
          "Symantec_AV_Logs": "Y",
          "TeamViewerLogs": "Y",
          "TeraCopy": "Y",
          "TorrentClients": "Y",
          "Torrents": "Y",
          "TotalAV": "Y",
          "TrendMicro": "Y",
          "USBDevicesLogs": "Y",
          "VIPRE": "Y",
          "VNCLogs": "Y",
          "Viber": "Y",
          "WBEM": "Y",
          "WSL": "Y",
          "WebBrowsers": "Y",
          "WebServers": "Y",
          "Webroot": "Y",
          "WhatsApp": "Y",
          "WindowsDefender": "Y",
          "WindowsIndexSearch": "Y",
          "WindowsNotificationsDB": "Y",
          "WindowsTimeline": "Y",
          "XPRestorePoints": "Y",
          "iTunesBackup": "Y",
          "mRemoteNG": "Y",
          "openSUSE": "Y"
         }
        }
      type: json
    - name: Template
      default: Reporting.Default
    - name: Password
    - name: Level
      default: "5"
      type: int
    - name: Format
      default: jsonl
    - name: OutputPrefix
    - name: target_args
      default: |-
        {
         "bucket": "",
         "GCSKey": "",
         "credentialsKey": "",
         "credentialsSecret": "",
         "region": "",
         "endpoint": "",
         "serverSideEncryption": ""
        }
      type: json
    sources:
    - query: |
        // Add all the tools we are going to use to the inventory.
        LET _ <= SELECT inventory_add(tool=ToolName, hash=ExpectedHash)
         FROM parse_csv(filename="/inventory.csv", accessor="me")
         WHERE log(message="Adding tool " + ToolName)

        LET baseline <= SELECT Fqdn FROM info()

        // Make the filename safe on windows but we trust the OutputPrefix.
        LET filename <= OutputPrefix + regex_replace(
            source=format(format="Collection-%s-%s",
                          args=[baseline[0].Fqdn,
                                timestamp(epoch=now()).MarshalText]),
            re="[^0-9A-Za-z\\-]", replace="_")

        LET _ <= log(message="Will collect package " + filename)
        LET report_filename <= if(condition=Template, then=filename + ".html")
        SELECT * FROM collect(artifacts=Artifacts, report=report_filename,
            args=Parameters, output=filename + ".zip", template=Template,
            password=Password, level=Level, format=Format)
  - name: Generic.Utils.FetchBinary
    parameters:
    - name: SleepDuration
      default: "0"
      type: int
    - name: ToolName
    - name: ToolInfo
    - name: IsExecutable
      type: bool
    sources:
    - query: |
        LET temp_binary <= tempfile(extension=".exe",
                 remove_last=TRUE, permissions="x")

        LET matching_tools = SELECT ToolName AS ArchiveTool, Filename
        FROM parse_csv(filename="/inventory.csv", accessor="me")

        SELECT * FROM foreach(row=matching_tools, query={
          SELECT copy(filename=Filename, accessor="me", dest=temp_binary) AS FullPath,
                      Filename AS Name
          FROM scope()
          WHERE ToolName = ArchiveTool
        })
```
Offline collector built on Ubuntu 20.04.03 LTS 

When I run the Offline Collector package on my test Windows 10 system, I get the following panic:

```
[INFO] 2021-09-22T15:43:34-05:00  Producing collection report at Collection-DESKTOP-6R9HSEP-2021-09-22T14_21_25-05_00.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x12a16f1]

goroutine 3910283 [running]:
www.velocidex.com/golang/velociraptor/search.getChildren(0xc0019c7de8, {0x28c9930, 0xc0003a2ac0})
        /home/mic/projects/velociraptor/search/index.go:193 +0x331
www.velocidex.com/golang/velociraptor/search.walkIndexWithPrefix.func1()
        /home/mic/projects/velociraptor/search/index.go:217 +0xee
created by www.velocidex.com/golang/velociraptor/search.walkIndexWithPrefix
        /home/mic/projects/velociraptor/search/index.go:214 +0x18f
```

**Comment by CdtDelta** [comment]
This was fixed in the latest CI build.
