### ISSUE TITLE
Adding client event monitoring from a notebook on Linux crashes Velociraptor

### ISSUE THREAD

**Issue by techev0** [Velocidex/velociraptor#1908]
When using the `add_client_monitoring()` function from a notebook on Linux builds the Velociraptor process crashes with the output shown below.

Sample VQL to reproduce:
* auditd packages are installed
* The label `test` exists on one host.
```
SELECT add_client_monitoring(artifact="Linux.Events.ProcessExecutions", label="test") FROM scope()
```

Adding `client_event` artifacts to the Client monitoring table through the `GUI` appears to work fine though, so the issue seems to be around Notebooks.

I have tried this using the `Linux.Events.ProcessExecutions` artifact, on the following builds:
* velociraptor-v0.6.4-2-linux-amd64  
* velociraptor-v0.6.5-linux-amd64

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16347fd]

goroutine 2087 [running]:
www.velocidex.com/golang/velociraptor/vql/server/monitoring.AddClientMonitoringFunction.Call({}, {0x1ffe6b8, 0xc000d32640}, {0x200d548, 0xc002560750}, 0x30dce30?)
	/home/mic/projects/velociraptor/vql/server/monitoring/add_monitoring.go:90 +0xa1d
www.velocidex.com/golang/vfilter.(*_SymbolRef).callFunction(0xc0020a5180, {0x1ffe6b8?, 0xc000d32640}, {0x200d548?, 0xc002560750}, {0x1ff5eb0?, 0x30dce30})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1962 +0x464
www.velocidex.com/golang/vfilter.(*_SymbolRef).Reduce(0xc0020a5180, {0x1ffe6b8, 0xc000d32640}, {0x200d548, 0xc002560750})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1803 +0x1c6
www.velocidex.com/golang/vfilter.(*_Value).Reduce(0xc001508fc0, {0x1ffe6b8, 0xc000d32640}, {0x200d548, 0xc002560750})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1622 +0x154
www.velocidex.com/golang/vfilter.(*_MemberExpression).Reduce(0xc0026b20a0, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1218 +0x55
www.velocidex.com/golang/vfilter.(*_MultiplicationExpression).Reduce(0xc0026b20c0, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1549 +0x52
www.velocidex.com/golang/vfilter.(*_AdditionExpression).Reduce(0xc0026b20e0, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1440 +0x52
www.velocidex.com/golang/vfilter.(*_ConditionOperand).Reduce(0xc00233b668, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1487 +0x85
www.velocidex.com/golang/vfilter.(*_OrExpression).Reduce(0xc0026b2100, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1394 +0x52
www.velocidex.com/golang/vfilter.(*_AndExpression).Reduce(0xc0026b2120, {0x1ffe6b8, 0xc000d32640}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:1352 +0x49
www.velocidex.com/golang/vfilter.(*_AliasedExpression).Reduce(0x0?, {0x1ffe6b8?, 0xc000d32640?}, {0x200d548?, 0xc002560750?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:730 +0x9e
www.velocidex.com/golang/vfilter.(*_SelectExpression).Transform.func2({0x1ffe6b8?, 0xc000d32640?}, {0xc002cce1c0?, 0x36?})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:984 +0x38
www.velocidex.com/golang/vfilter.MaterializedLazyRow({0x1ffe6b8, 0xc000d32640}, {0x19ce680?, 0xc000375810?}, {0x200d548, 0xc0025606c0})
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/lazy.go:96 +0x1d0
www.velocidex.com/golang/vfilter.(*_Select).processSingleRow(0xc001537500, {0x1ffe6b8, 0xc000d32640}, {0x200d548, 0xc000d1cbd0}, {0x1bf7f20, 0xc000d1cbd0}, 0xc002ab3aa0)
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:624 +0x412
www.velocidex.com/golang/vfilter.(*_Select).Eval.func3()
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:603 +0xe5
created by www.velocidex.com/golang/vfilter.(*_Select).Eval
	/home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220428152704-2c10e2e5806d/vfilter.go:588 +0x2ca
```

**Comment by scudette** [comment]
A workaround for older releases is to provide an empty parameters dict:
```sql
SELECT add_client_monitoring(artifact="Linux.Events.ProcessExecutions", label="test", parameters=dict()) 
FROM scope()
```
