### ISSUE TITLE
Crash while running Windows.Packs.LateralMovement in offline collector

### ISSUE THREAD

**Issue by colindix** [Velocidex/velociraptor#1934]
Can't say what the memory usage was at the time of the crash, however when I had looked a few mins before it was only around 135MB, not sure if this one is substantially more mem intensive. Not sure if it makes a difference, but the config had a reasonable amount of artifacts in it, but the collector had only produced ~2MB zip file at time of crash.
Hope this is helpful.

```
[INFO] 2022-07-11T22:45:46+10:00 Starting collection of Windows.Packs.LateralMovement/WMIC
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1dad5ef]

goroutine 731615 [running]:
www.velocidex.com/golang/go-prefetch.PrefixCodeTreeDecodeSymbol(0xc006fc3ddb?, 0x2bd9b?)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20200722101157-37e4751dd5ca/lzxpress.go:193 +0xaf
www.velocidex.com/golang/go-prefetch.LZXpressHuffmanDecompressChunk(0x5ddb, {0xc006fbe000, 0x31b76, 0x32000}, 0x20004, {0xc0070f6000, 0x31b76, 0xc0035eeec0?}, 0x10000)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20200722101157-37e4751dd5ca/lzxpress.go:219 +0x1fb
www.velocidex.com/golang/go-prefetch.LZXpressHuffmanDecompress({0xc006fbe000, 0x31b76, 0x32000}, 0x31b76)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20200722101157-37e4751dd5ca/lzxpress.go:299 +0x90
www.velocidex.com/golang/go-prefetch.LZXpressHuffmanDecompressWithFallback({0xc006fbe000, 0x31b76, 0x32000}, 0x31b76)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20200722101157-37e4751dd5ca/lzxpress_windows.go:41 +0x1af
www.velocidex.com/golang/velociraptor/vql/parsers.(*LZXpressFunction).Call(0xc002d8c998?, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?}, 0x5700000069?)
        /home/mic/projects/velociraptor/vql/parsers/lzxpress.go:31 +0x148
www.velocidex.com/golang/vfilter.(*_SymbolRef).callFunction(0xc0024d6a50, {0x2be52a8?, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00}, {0x2bdb8d0?, 0x387ecf8})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1945 +0x514
www.velocidex.com/golang/vfilter.(*_SymbolRef).Reduce(0xc0024d6a50, {0x2be52a8, 0xc00012a058}, {0x2bf46a8, 0xc0066a3b00})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1805 +0x1c6
www.velocidex.com/golang/vfilter.(*_Value).Reduce(0xc002401020, {0x2be52a8, 0xc00012a058}, {0x2bf46a8, 0xc0066a3b00})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1624 +0x154
www.velocidex.com/golang/vfilter.(*_MemberExpression).Reduce(0xc004f1f5c0, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1218 +0x55
www.velocidex.com/golang/vfilter.(*_MultiplicationExpression).Reduce(0xc004f1f5e0, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1551 +0x52
www.velocidex.com/golang/vfilter.(*_AdditionExpression).Reduce(0xc004f1f620, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1442 +0x52
www.velocidex.com/golang/vfilter.(*_ConditionOperand).Reduce(0xc000117de8, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1489 +0x85
www.velocidex.com/golang/vfilter.(*_OrExpression).Reduce(0xc004f1f640, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1394 +0x55
www.velocidex.com/golang/vfilter.(*_AndExpression).Reduce(0xc004f1f660, {0x2be52a8, 0xc00012a058}, {0x2bf46a8?, 0xc0066a3b00?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1352 +0x49
www.velocidex.com/golang/vfilter.(*Lambda).Reduce(0xc004f1f340, {0x2be52a8, 0xc00012a058}, {0x2bf46a8, 0xc0066a3a70}, {0xc0074e5718, 0x1?, 0xc000116708?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/lambda.go:55 +0x245
www.velocidex.com/golang/vtypes.(*ValueParser).Parse(0xc000116708, {0x2bf46a8, 0xc0066a3a70}, {0xc004f24ed8?, 0xc9cd94?}, 0xc004f24ea0?)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vtypes@v0.0.0-20220107071957-49947f744c34/value.go:52 +0xde
www.velocidex.com/golang/vtypes.(*ParseAtOffset).Parse(0xc004051b00, {0x2bf46a8, 0xc0066a3a70}, {0x2bd4d60, 0xc004cb31e0}, 0x0)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vtypes@v0.0.0-20220107071957-49947f744c34/struct.go:104 +0xad
www.velocidex.com/golang/vtypes.(*StructObject).Get(0xc0020c34c0, {0xc0041b8e60, 0xc})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vtypes@v0.0.0-20220107071957-49947f744c34/struct.go:146 +0xda
www.velocidex.com/golang/vtypes.StructAssociative.Associative({}, {0x1156720?, 0xc00688d200?}, {0x26391c0?, 0xc0020c34c0?}, {0x246f6c0?, 0xc0066b52d0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vtypes@v0.0.0-20220107071957-49947f744c34/protocol.go:49 +0x196
www.velocidex.com/golang/vfilter/protocols.(*AssociativeDispatcher).Associative(0xc00688d2f8, {0x2bf46a8, 0xc0066a35f0}, {0x26391c0?, 0xc0020c34c0}, {0x246f6c0?, 0xc0066b52d0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/protocols/protocol_associative.go:94 +0x604
www.velocidex.com/golang/vfilter/scope.(*Scope).Associative(0xc0041b8e60?, {0x26391c0?, 0xc0020c34c0?}, {0x246f6c0?, 0xc0066b52d0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/scope/scope.go:275 +0x53
www.velocidex.com/golang/vfilter.(*_MemberExpression).Reduce(0xc004ce4580, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1250 +0xee
www.velocidex.com/golang/vfilter.(*_MultiplicationExpression).Reduce(0xc004ce45a0, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1551 +0x52
www.velocidex.com/golang/vfilter.(*_AdditionExpression).Reduce(0xc004ce45c0, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1442 +0x52
www.velocidex.com/golang/vfilter.(*_ConditionOperand).Reduce(0xc0016cdd40, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1489 +0x85
www.velocidex.com/golang/vfilter.(*_OrExpression).Reduce(0xc004ce45e0, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1394 +0x55
www.velocidex.com/golang/vfilter.(*_AndExpression).Reduce(0xc004ce4600, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:1352 +0x49
www.velocidex.com/golang/vfilter.(*_AliasedExpression).Reduce(0x0?, {0x2be5270?, 0xc001bdfc80?}, {0x2bf46a8?, 0xc0066a35f0?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:730 +0x9e
www.velocidex.com/golang/vfilter.(*_SelectExpression).Transform.func2({0x2be5270?, 0xc001bdfc80?}, {0xc0041b8e5c?, 0x4?})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:984 +0x38
www.velocidex.com/golang/vfilter.MaterializedLazyRow({0x2be5270, 0xc001bdfc80}, {0x2586f40?, 0xc00037c540?}, {0x2bf46a8, 0xc0066a3710})
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/lazy.go:96 +0x1d0
www.velocidex.com/golang/vfilter.(*_Select).processSingleRow(0xc00120e3c0, {0x2be5270, 0xc001bdfc80}, {0x2bf46a8, 0xc0066a33b0}, {0x27bcc40, 0xc0066a33b0}, 0xc00244c1e0)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:645 +0x298
www.velocidex.com/golang/vfilter.(*_Select).Eval.func3()
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:603 +0xe5
created by www.velocidex.com/golang/vfilter.(*_Select).Eval
        /home/mic/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220606015754-7f03acba2fc4/vfilter.go:588 +0x2ca
```

**Comment by scudette** [comment]
This looks like a corrupted prefetch file that caused a crash while recompressing it. Thanks for reporting.
