### ISSUE TITLE
Crash when calling user_grant with user parameter not as string

### ISSUE THREAD

**Issue by BadBloopZ** [Velocidex/velociraptor#2022]
Velociraptor crashes when we try to call the user_grant function and handing over the user parameter not as string, e.g.
`SELECT user_grant(user=testuser, roles='administrator', orgs='3') FROM scope()` instead of
`SELECT user_grant(user='testuser', roles='administrator', orgs='3') FROM scope()`

This was reproducible via API and VQL notebook.

I guess we should add input validation / type checking to catch the error and provide an error message to the user.

Full error trace:
```
[INFO] 2022-08-27T10:40:42Z Query API call {"arg":{"Query":[{"Name":"IRIS-VELO-ORG-3-ASSIGN-USER-testuser","VQL":"SELECT user_grant(user=testuser, roles='administrator', orgs='3') FROM scope()"}],"max_row":100,"max_wait":1},"org":"","user":"iris-modules"}
[INFO] 2022-08-27T10:40:42Z Query: Running SELECT user_grant(user=testuser, roles='administrator', orgs='3') FROM scope()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x16620b7]

goroutine 24050 [running]:
www.velocidex.com/golang/velociraptor/vql/server/users.GrantFunction.Call.func1(...)
        /home/runner/work/velociraptor/velociraptor/vql/server/users/grant.go:90
www.velocidex.com/golang/velociraptor/vql/server/users.GrantFunction.Call({}, {0x2038ad0, 0xc0016d01c0}, {0x2047e48, 0xc0018fbef0}, 0x315d210?)
        /home/runner/work/velociraptor/velociraptor/vql/server/users/grant.go:99 +0x7f7
www.velocidex.com/golang/vfilter.(*_SymbolRef).callFunction(0xc00200f9f0, {0x2038ad0?, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0}, {0x20302a8?, 0x315d210})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1983 +0x4c4
www.velocidex.com/golang/vfilter.(*_SymbolRef).Reduce(0xc00200f9f0, {0x2038ad0, 0xc0016d01c0}, {0x2047e48, 0xc0018fbef0})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1818 +0x1c6
www.velocidex.com/golang/vfilter.(*_Value).Reduce(0xc001ffcc00, {0x2038ad0, 0xc0016d01c0}, {0x2047e48, 0xc0018fbef0})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1637 +0x154
www.velocidex.com/golang/vfilter.(*_MemberExpression).Reduce(0xc001333380, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1231 +0x55
www.velocidex.com/golang/vfilter.(*_MultiplicationExpression).Reduce(0xc0013333a0, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1564 +0x52
www.velocidex.com/golang/vfilter.(*_AdditionExpression).Reduce(0xc0013333c0, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1455 +0x52
www.velocidex.com/golang/vfilter.(*_ConditionOperand).Reduce(0xc0018aea50, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1502 +0x85
www.velocidex.com/golang/vfilter.(*_OrExpression).Reduce(0xc0013333e0, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1407 +0x55
www.velocidex.com/golang/vfilter.(*_AndExpression).Reduce(0xc001333400, {0x2038ad0, 0xc0016d01c0}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:1365 +0x49
www.velocidex.com/golang/vfilter.(*_AliasedExpression).Reduce(0x40?, {0x2038ad0?, 0xc0016d01c0?}, {0x2047e48?, 0xc0018fbef0?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:732 +0x9e
www.velocidex.com/golang/vfilter.(*_SelectExpression).Transform.func2({0x2038ad0, 0xc0016d01c0}, {0xc000fb6e00?, 0x35?})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:986 +0x46
www.velocidex.com/golang/vfilter.MaterializedLazyRow({0x2038ad0, 0xc0016d01c0}, {0x19fe5a0?, 0xc0003a0230?}, {0x2047e48, 0xc0019b1ef0})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/lazy.go:96 +0x1d0
www.velocidex.com/golang/vfilter.(*_Select).processSingleRow(0xc0016d0340, {0x2038ad0, 0xc0016d01c0}, {0x2047e48, 0xc001bbd710}, {0x1c2db60, 0xc001bbd710}, 0xc00181ad80)
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:624 +0x412
www.velocidex.com/golang/vfilter.(*_Select).Eval.func3()
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:603 +0xe5
created by www.velocidex.com/golang/vfilter.(*_Select).Eval
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/vfilter.go:588 +0x2ca
```

**Comment by BadBloopZ** [comment]
Suggestion: Add a type check to the GrantFunction in grant.go before it is used (I think before line 48). However, I have no experience with Go so please treat with caution.

```go
username, ok := arg.Username.(string)
if !ok {
	scope.Log("user_grant: Parameter 'user' was not of type string")
	return vfilter.Null{}
}
```
