### ISSUE TITLE
Crash with 0.6.6-2 32 bit binary

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2194]
Crashes with unaligned access:

```
C:\Users\test\Downloads>velociraptor-v0.6.6-2-windows-386.exe --config c:\Users\test\AppData\Local\Temp\client.config.yaml client -v
[INFO] 2022-10-27T23:18:45-07:00  _    __     __           _                  __
[INFO] 2022-10-27T23:18:45-07:00 | |  / /__  / /___  _____(_)________ _____  / /_____  _____
[INFO] 2022-10-27T23:18:45-07:00 | | / / _ \/ / __ \/ ___/ / ___/ __ `/ __ \/ __/ __ \/ ___/
[INFO] 2022-10-27T23:18:45-07:00 | |/ /  __/ / /_/ / /__/ / /  / /_/ / /_/ / /_/ /_/ / /
[INFO] 2022-10-27T23:18:45-07:00 |___/\___/_/\____/\___/_/_/   \__,_/ .___/\__/\____/_/
[INFO] 2022-10-27T23:18:45-07:00                                   /_/
[INFO] 2022-10-27T23:18:45-07:00 Digging deeper!                  https://www.velocidex.com
[INFO] 2022-10-27T23:18:45-07:00 This is Velociraptor 0.6.6-2 built on 2022-09-10T01:54:38Z (ebaf185)
[INFO] 2022-10-27T23:18:45-07:00 Loading config from file c:\Users\test\AppData\Local\Temp\client.config.yaml
[INFO] 2022-10-27T23:18:45-07:00 Loading writeback from C:\Users\test\AppData\Local\Temp\Velociraptor.writeback.yaml
[INFO] 2022-10-27T23:18:45-07:00 Setting temp directory to C:\Users\test\AppData\Local\Temp\temp
[INFO] 2022-10-27T23:18:45-07:00 Starting Org Manager service.
[INFO] 2022-10-27T23:18:45-07:00 Starting nanny with MaxConnectionDelay 10m0s and MaxMemoryHardLimit 0
[INFO] 2022-10-27T23:18:45-07:00 Starting services for Root Org
[INFO] 2022-10-27T23:18:45-07:00 Starting Journal service for Root Org.
[INFO] 2022-10-27T23:18:45-07:00 Starting the notification service for Root Org.
[INFO] 2022-10-27T23:18:45-07:00 Starting repository manager for Root Org
[INFO] 2022-10-27T23:18:46-07:00 Loaded 345 built in artifacts in 460.0687ms
[INFO] 2022-10-27T23:18:46-07:00 Installing Dummy inventory_service. Will download tools to temp directory.
[INFO] 2022-10-27T23:18:46-07:00 Starting Crypto for client C.7792d40a1992f30d
[INFO] 2022-10-27T23:18:46-07:00 Expecting self signed certificate for server.
[INFO] 2022-10-27T23:18:46-07:00 Starting event query service with version 0.
[INFO] 2022-10-27T23:18:46-07:00 Starting HTTPCommunicator: HTTP Connector to [https://localhost:8000/]
[INFO] 2022-10-27T23:18:46-07:00 Starting monitoring query $305eaa7914d4fe025e020c27ed8ab856815fc518a5584ce2e0b7b773cd2b9df8
[INFO] 2022-10-27T23:18:46-07:00 Starting monitoring query $305eaa7914d4fe025e020c27ed8ab856815fc518a5584ce2e0b7b773cd2b9df8
panic: unaligned 64-bit atomic operation

goroutine 101 [running]:
runtime/internal/atomic.panicUnaligned()
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x1577e79c)
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/internal/atomic/atomic_386.s:225 +0x10
www.velocidex.com/golang/velociraptor/responder.(*Responder).Log(0x1577e780, {0x24614cc, 0x14e17a40}, {0x15e38230, 0x5}, {0x15e38236, 0x66}, {0x0, 0x0, 0x0})
        /home/runner/work/velociraptor/velociraptor/responder/responder.go:196 +0x38
www.velocidex.com/golang/velociraptor/actions.(*LogWriter).Write(0x15da95a0, {0x15e381c0, 0x6c, 0x70})
        /home/runner/work/velociraptor/velociraptor/actions/vql.go:54 +0x8a
log.(*Logger).Output(0x151f00f0, 0x2, {0x15e38150, 0x6b})
        /opt/hostedtoolcache/go/1.18.4/x64/src/log/log.go:195 +0x27f
log.(*Logger).Print(0x151f00f0, {0x15d83f84, 0x1, 0x1})
        /opt/hostedtoolcache/go/1.18.4/x64/src/log/log.go:214 +0x72
www.velocidex.com/golang/vfilter/scope.(*protocolDispatcher).Log(0x156fa240, {0x20b1ec5, 0x15}, {0x158d8160, 0x1, 0x1})
        /home/runner/go/pkg/mod/www.velocidex.com/golang/vfilter@v0.0.0-20220821025017-911b14d15652/scope/dispatcher.go:194 +0xcf
```

This issue is fixed in 0.6.7-rc1 and only affects 32 bit binaries.

**Comment by scudette** [comment]
Fixed by #2195 and a new 0.6.6-3 build is available
