### ISSUE TITLE
Segfault when using client_delete

### ISSUE THREAD

**Issue by hendrkss** [Velocidex/velociraptor#3958]
Hello, 
we are having Velociraptor v0.73.3 and using the new "Metadata Indexing" Feature. 

When executing the client_delete plugin with "really_do_it=True" our Velociraptor server ist crashing. Anybody else having this issue?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0xe07320]
goroutine 2776 [running]:
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).updateClientMetadataIndex.func1(0x0)
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:144 +0x60
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).Modify(0xc007b043a0, {0x39b98b0?, 0x289a4e0?}, 0xc0008b62c0, {0xc0336c000e?, 0x12?}, 0xc03978fde8)
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/storage.go:113 +0x122
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).updateClientMetadataIndex(0xc007b043a0, {0x28c0160, 0xc001092000}, 0xc0008b62c0, {0xc0336c000e, 0x12}, 0xc0ef098740)
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:138 +0x165
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).houseKeepMetadataIndex(0xc007b043a0, {0x28c0160, 0xc001092000}, 0xc0008b62c0, {0xc0336c000e, 0x12})
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:120 +0x65
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).houseKeep(0xc007b043a0, {0x28c0160, 0xc001092000}, 0xc0008b62c0)
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:76 +0x119
www.velocidex.com/golang/velociraptor/services/client_info.(*Store).StartHouseKeep.func1()
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:47 +0x18b
created by www.velocidex.com/golang/velociraptor/services/client_info.(*Store).StartHouseKeep in goroutine 1
        /builds/linux-packages/pkg-velociraptor-server/upstream-src/services/client_info/housekeep.go:33 +0xdf
```

**Comment by scudette** [comment]
this seems to be a bug that occurs because the server attempts to update the metadata for a client which had been deleted.

Fix should be in #3959 - I will backport to 0.73 branch too. Thanks for reporting it

**Comment by hendrkss** [comment]
Fix works, thanks!
