### ISSUE TITLE
www.velocidex.com/golang/go-ntfs/parser.FixUpDiskMFTEntry fails

### ISSUE THREAD

**Issue by op7ic** [Velocidex/velociraptor#535]
Hi Team, 

I noticed that MFT entry grab fails. Here is my config file:
```
autoexec:
  argv: ["artifacts", "collect", "-v", "Windows.KapeFiles.Targets",
         "--output", "collection_$COMPUTERNAME.zip",
         "--args", "WebBrowsers=Y",
         "--args", "_BasicCollection=Y",
         "--args", "WBEM=Y",
         "--args", "WER=Y",
         "--args", "WindowsDefender=Y",
         "--args", "TrendMicro=Y",
         "--args", "TeamViewerLogs=Y",
         "--args", "WebBrowsers=Y",
         "--args", "MOF=Y",
         "--args", "VSSAnalysis=Y"]
```

Using above config I compile into new collector:

```
velociraptor-v0.4.7-windows-386.exe config repack myconfig.txt mycapture.exe
```

Here is output when I execute mycapture.exe:
```
panic: runtime error: index out of range [2046] with length 1912

goroutine 17926 [running]:
www.velocidex.com/golang/go-ntfs/parser.FixUpDiskMFTEntry(0x15243d4c, 0x2c, 0x2c, 0x14850540, 0x26f0364)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-ntfs@v0.0.0-20200726152114-40b3dfbc3d5c/parser/boot.go:57 +0x4af
www.velocidex.com/golang/go-ntfs/parser.(*NTFSContext).GetMFT(0x1526b230, 0x302c0, 0x0, 0x24978a4, 0xb21fb7cc, 0xb21fb7cc)
        /home/mic/go/pkg/mod/www.velocidex.com/golang/go-ntfs@v0.0.0-20200726152114-40b3dfbc3d5c/parser/context.go:36 +0xb0
www.velocidex.com/golang/velociraptor/vql/windows/filesystems.(*LazyNTFSFileInfo).ensureCachedInfo(0x15e90cc0)
        /home/mic/projects/velociraptor/vql/windows/filesystems/ntfs_lazy_windows.go:110 +0x66
www.velocidex.com/golang/velociraptor/vql/windows/filesystems.(*LazyNTFSFileInfo).IsDir(0x15e90cc0, 0x40d100)
        /home/mic/projects/velociraptor/vql/windows/filesystems/ntfs_lazy_windows.go:123 +0x21
www.velocidex.com/golang/velociraptor/glob.is_dir_or_link(0x1a80c00, 0x15e90cc0, 0x1a79700, 0x1543b030, 0x0, 0x16c29900)
        /home/mic/projects/velociraptor/glob/glob.go:241 +0x4f
www.velocidex.com/golang/velociraptor/glob.Globber.ExpandWithContext.func1(0x157afe80, 0x1a79700, 0x1543b030, 0x17604f80, 0x78, 0x14be8a80, 0x1493b1a0, 0x1a714a0, 0x1491dfa0)
        /home/mic/projects/velociraptor/glob/glob.go:296 +0x250
created by www.velocidex.com/golang/velociraptor/glob.Globber.ExpandWithContext
        /home/mic/projects/velociraptor/glob/glob.go:258 +0x8d
```

Version:
```
(latest) velociraptor-v0.4.7-windows-386
```

**Comment by scudette** [comment]
I think this was fixed really recently https://github.com/Velocidex/go-ntfs/commit/9f050df195aaa03709517bc582fcddee9d9f904f - it might be the same crash.

We should resync and see if it fixes.

**Comment by scudette** [comment]
This should be fixed in CI builds and will be out next release.
