### ISSUE TITLE
[Bug] flow_results() in notebook crashes server

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#589]
Hi,

we ran the following VQL in the notebook which caused the following exception and crashed our vraptor server:

```
SELECT * FROM flow_results(client_id="C.dd1583d805230e2d", flow_id="F.BT1DFM1IOJ446")
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xfcd598]

goroutine 908 [running]:
www.velocidex.com/golang/velociraptor/vql/server.FlowResultsPlugin.Call.func1(0xc0031437a0, 0xc000b16b40, 0xc000d22fc0, 0x1bac480, 0xc000d22f00)
	/home/mic/velociraptor/vql/server/results.go:278 +0x758
created by www.velocidex.com/golang/velociraptor/vql/server.FlowResultsPlugin.Call
	/home/mic/velociraptor/vql/server/results.go:247 +0x84
```

**Comment by scudette** [comment]
Thanks for reporting. This happens when the flow does not actually exist and no artifact is specified. It is trying to fetch the flow record to figure out what the artifact the flow was collecting was.
